# Generated by Django 2.2.1 on 2019-06-03 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SliderTop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_img', models.ImageField(blank=True, null=True, upload_to='random_img')),
                ('slider_caption', models.CharField(blank=True, max_length=20, null=True)),
                ('slider_description', models.CharField(blank=True, max_length=30, null=True)),
                ('slider_description2', models.CharField(blank=True, max_length=30, null=True)),
                ('slider_button', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
