# Generated by Django 2.2.1 on 2019-06-03 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_work'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeopleSay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people_say', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
