# Generated by Django 2.2.1 on 2019-06-03 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_peoplesay'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(blank=True, max_length=10, null=True)),
                ('area', models.CharField(blank=True, max_length=10, null=True)),
                ('living', models.CharField(blank=True, max_length=10, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('button', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
