# Generated by Django 2.2.1 on 2019-06-04 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_pricesection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foot_pth', models.ImageField(blank=True, null=True, upload_to='foot')),
                ('feature', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateTimeField(default=None)),
                ('comment', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
