# Generated by Django 2.2.1 on 2019-06-13 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateTimeField(default=None)),
                ('blog_comment', models.CharField(blank=True, max_length=20, null=True)),
                ('blog_description', models.TextField(blank=True, null=True)),
                ('blog_button', models.CharField(blank=True, max_length=15, null=True)),
                ('blog_img', models.ImageField(blank=True, null=True, upload_to='blog')),
            ],
        ),
    ]
